### ISSUE TITLE
catboost conda support

### ISSUE THREAD

**Issue by prabodh1194** [Snowflake-Labs/catboost-udf#1]
Thanks for the great repo! We have been waiting for snowpark to support catboost. However, this list -- https://repo.anaconda.com/pkgs/snowflake/ doesn't list snowpark as a supported package.

In that case, how does this UDF work?

**Comment by sfc-gh-dturnbull** [comment]
Catboost supports exporting a trained model as a pure python function in a file. 

[cb.py Line 39](https://github.com/Snowflake-Labs/catboost-udf/blob/main/cb.py#L39)
`model.save_model("catboost_model_export.py", format="python")`

The code then imports this and uses it in the udf:

`import catboost_model_export as cbm`
