### ISSUE TITLE
Catboost for training on Snowpark

### ISSUE THREAD

**Issue by rahulmisal27** [Snowflake-Labs/catboost-udf#2]
Does anyone tried catboost for training on snowpark?

**Comment by thiernmad** [comment]
yes I'm currently using it. There was a recent [release of Snowflake](https://docs.snowflake.com/en/release-notes/clients-drivers/snowpark-ml-2024#version-1-4-1-2024-04-18) that added support for Catboost.
Everything seems OK now

**Comment by rahulmisal27** [comment]
Thank you @thiernmad !

**Comment by rahulmisal27** [comment]
@thiernmad Have you tried training the catboost model on Snowpark itself? We got the unable to create catboost_info error.
